name: legado_app
description: "Una aplicación Flutter para experiencias culturales mexicanas auténticas."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.2.0
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.4
  location: ^5.0.3
  http: ^1.2.1
  flutter_dotenv: ^5.1.0
  geolocator: ^10.1.0
  firebase_core: ^3.0.0
  # Cloud Firestore para la base de datos NoSQL
  cloud_firestore: ^5.0.0
  # Firebase Auth para la autenticación de usuarios
  firebase_auth: ^5.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Assets para la aplicación
  assets:
    - assets/